---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention 
summary: NetApp SnapMirror 可通过 LAN 或 WAN 高速复制数据，从而在虚拟和传统环境中实现高数据可用性和快速数据复制。在将数据复制到 NetApp 存储系统并持续更新二级数据时，您的数据将保持最新，并在需要时保持可用。不需要外部复制服务器。 
---
= 了解复制服务
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror 可通过 LAN 或 WAN 高速复制数据，从而在虚拟和传统环境中实现高数据可用性和快速数据复制。在将数据复制到 NetApp 存储系统并持续更新二级数据时，您的数据将保持最新，并在需要时保持可用。不需要外部复制服务器。



== 功能

* 在 ONTAP 存储系统之间复制数据，以支持将数据备份和灾难恢复到云或云之间。
* 确保灾难恢复环境的可靠性和高可用性。
* ONTAP 存储之间的高效块级复制速度快，效率高，灾难恢复和备份都有精细的恢复点。




== 成本

NetApp 不会因使用复制服务而向您收取费用，但您需要向云提供商咨询适用的数据传入和传出费用。



== 支持的工作环境

BlueXP支持在以下类型的工作环境之间进行数据复制。

[cols="30,30"]
|===
| 源工作环境 | 支持的目标工作环境 


| Cloud Volumes ONTAP  a| 
* 适用于 ONTAP 的 Amazon FSX
* Cloud Volumes ONTAP
* 内部 ONTAP 集群




| 内部 ONTAP 集群  a| 
* 适用于 ONTAP 的 Amazon FSX
* Cloud Volumes ONTAP
* 内部 ONTAP 集群




| 适用于 ONTAP 的 Amazon FSX  a| 
* 适用于 ONTAP 的 Amazon FSX
* Cloud Volumes ONTAP
* 内部 ONTAP 集群


|===


== 数据复制的工作原理

BlueXP使用SnapMirror和SnapVault 技术简化了不同ONTAP 系统上卷之间的数据复制。您只需标识源卷和目标卷、然后选择复制策略和计划即可。

对于Cloud Volumes ONTAP 、BlueXP会购买所需的磁盘、配置关系、应用复制策略、然后在卷之间启动基线传输。


NOTE: 基线传输包括源数据的完整副本。后续传输包含源数据的差异副本。



== 支持的数据保护配置

BlueXP支持简单、扇出和级联数据保护配置：

* 在简单的配置中、从卷 A 复制到卷 B
* 在扇出配置中、从卷 A 复制到多个目标。
* 在级联配置中、从卷 A 复制到卷 B 、从卷 B 复制到卷 C




== 使用BlueXP备份和恢复复制数据

从BlueXP Connector 3.9.31版开始、您可以通过BlueXP备份和恢复功能使用SnapMirror和SnapVault技术在不同ONTAP系统上的卷之间复制数据。因此、如果您计划将数据复制到其他ONTAP系统、并且还希望为同一数据创建备份到对象存储、则可能需要使用 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["BlueXP备份和恢复"^] 这样、您只需一项服务即可管理数据保护需求。

目前、以下功能仅在BlueXP复制服务中受支持-使用BlueXP备份和恢复的复制功能时不受支持。

* 不支持级联配置、即先从卷A复制到卷B、然后再从卷B复制到卷C
* 不支持将数据复制到FSx for ONTAP系统或从FSx for FSx复制数据。
* 不支持创建卷的一次性复制。


因此、如果您需要任何此功能、请使用BlueXP复制。
